### ISSUE TITLE
Whitelisting by IP subnet

### ISSUE THREAD

**Issue by MavEtJu** [foudfou/skipCertError#23]
Hello,

We would like to "whitelist" a whole IP subnet for our testnet, for example "10.72.*".
Could you please add this feature, it would save me a lot of hassle.

Edwin

**Comment by viktorlindgren** [comment]
I would like this also. Waiting until the extension is updated at mozilla addons page.

**Comment by foudfou** [comment]
I just uploaded v0.4.4 on AMO.

**Comment by viktorlindgren** [comment]
Thx!
