### ISSUE TITLE
not working reliably in FF37.0.1

### ISSUE THREAD

**Issue by jauling** [foudfou/skipCertError#24]
Since upgrading to FF37.0.1, on OSX 10.10, the skipcert doesn't seem to always be working. For some reason, for the sites that are not automatically skipping the cert, clicking on the "Add Exception" standard button does nothing. I'm not sure if this is an issue with the plugin, or FF37.0.1, or both?

**Comment by jauling** [comment]
actually, even after disabling skipCert, the "Add Exception" button still doesn't work. There must be something wrong with FF on my side... Can anyone else confirm otherwise?

**Comment by jauling** [comment]
This looks to be directly related. FF38 may solve the problem.

https://support.mozilla.org/en-US/questions/1049682

**Comment by foudfou** [comment]
Thank you for the detective work. I'm closing this one then.

**Comment by jauling** [comment]
actually, I had to rollback to FF36.0.4, but yea.. it seems newer FF has some issues.
