### ISSUE TITLE
Support for expired certificates

### ISSUE THREAD

**Issue by Rock5** [foudfou/skipCertError#9]
Can you add support for expired certificates?

**Comment by pLum0** [comment]
+1

**Comment by foudfou** [comment]
Hi, I don't think this is feasible: sec_error_revoked_certificate triggers a *neterror* (like `about:neterror?e=nssFailure2&u=https%3A//lavabit.com/&c=UTF-8&f=regular&d=An%20error%20occurred%20during%20a%20connection%20to%20lavabit.com.%0A%0APeer%27s%20Certificate%20has%20been%20revoked.%0A%0A%28Error%20code%3A%20sec_error_revoked_certificate%29%0A`) which can *not* be overridden by nsICertOverrideService. In other words, no exception can be added for this type of errors.
I'll close this issue, but feel free to reopen it if I'm wrong.
